<?PHP
//Llamado de coor_actualiza_datos_est.php
$consulta = "SELECT EST_COD,
	EST_NOMBRE,
	EST_NRO_IDEN,
	EST_DIRECCION,
	EST_TELEFONO,
	EST_ZONA_POSTAL,
	EST_SEXO,
	EOT_TIPOSANGRE,
	EOT_RH,
	EOT_EMAIL,
	EOT_ESTADO_CIVIL,
	TEC_NOMBRE,
	TO_CHAR(EOT_FECHA_NAC, 'DD-MM-YYYY'),
	EOT_COD_LUG_NAC,
	LUG_NOMBRE,
	CRA_NOMBRE,
	EST_VALOR_MATRICULA,
	ESTADO_NOMBRE,
	EOT_EMAIL_INS,
	EST_PEN_NRO,
	EST_IND_CRED,
	DECODE(TRIM(EST_IND_CRED),'S','Creditos','N','Horas'),
	est_acuerdo,
        est_cra_cod,
        trim(EST_ESTADO_EST) EST_ESTADO_EST,
        EST_TIPO_IDEN
	FROM ACEST,ACESTOTR,GETIPESCIVIL,GELUGAR,ACCRA,ACESTADO
	WHERE EST_COD = EOT_COD
	AND EST_CRA_COD = CRA_COD
	AND EOT_ESTADO_CIVIL = TEC_CODIGO(+)
	AND EOT_COD_LUG_NAC = LUG_COD(+)
	AND ESTADO_COD = EST_ESTADO_EST
	AND EST_COD =".$_REQUEST['estcod']."
	AND EST_CRA_COD IN(SELECT cra_cod 
	FROM accra 
	WHERE cra_emp_nro_iden = $usuario)";
//Llamado de coor_actualiza_datos_est.php
$consulta_asistente = "SELECT EST_COD,
	EST_NOMBRE,
	EST_NRO_IDEN,
	EST_DIRECCION,
	EST_TELEFONO,
	EST_ZONA_POSTAL,
	EST_SEXO,
	EOT_TIPOSANGRE,
	EOT_RH,
	EOT_EMAIL,
	EOT_ESTADO_CIVIL,
	TEC_NOMBRE,
	TO_CHAR(EOT_FECHA_NAC, 'DD-MM-YYYY'),
	EOT_COD_LUG_NAC,
	LUG_NOMBRE,
	CRA_NOMBRE,
	EST_VALOR_MATRICULA,
	ESTADO_NOMBRE,
	EOT_EMAIL_INS,
	EST_PEN_NRO,
	EST_IND_CRED,
	DECODE(TRIM(EST_IND_CRED),'S','Creditos','N','Horas'),
	est_acuerdo,
        est_cra_cod,
        trim(EST_ESTADO_EST) EST_ESTADO_EST,
        EST_TIPO_IDEN
	FROM ACEST,ACESTOTR,GETIPESCIVIL,GELUGAR,ACCRA,ACESTADO
	WHERE EST_COD = EOT_COD
	AND EST_CRA_COD = CRA_COD
	AND EOT_ESTADO_CIVIL = TEC_CODIGO(+)
	AND EOT_COD_LUG_NAC = LUG_COD(+)
	AND ESTADO_COD = EST_ESTADO_EST
	AND EST_COD =".$_REQUEST['estcod'];
?>
