<?PHP
//ARP
$QryArp = "SELECT ARP_NOMBRE, ARP_DIRECCION, ARP_TELEFONO   
	FROM PEEMPARP,PEARP
	WHERE ARP_COD = EAR_ARP_COD
	AND EAR_EMP_COD = '".$_SESSION["fun_cod"]."'
	 and ear_estado='A'";
	
//EPS
$QryEps = "SELECT EPS_NOMBRE, EPS_DIRECCION, EPS_TELEFONO
	FROM PEEMPEPS,PEEPS
	WHERE EPS_COD = EPE_EPS_COD
	AND EPE_EMP_COD = '".$_SESSION["fun_cod"]."'
	AND epe_estado='A'";

//FONDO DE PENSIONES
$QryFondo = "SELECT FPE_NOMBRE, FPE_DIRECCION, FPE_TELEFONO
	FROM PEEMPFONPEN,PEFONPEN
	WHERE FPE_COD = EFP_FPE_COD
	AND EFP_EMP_COD = '".$_SESSION["fun_cod"]."'
	AND efp_estado='A'";

//CAJA DE COMPENSACIO
$QryCaja = "SELECT CCO_NOMBRE, CCO_DIRECCION, CCO_TELEFONO
	FROM PEEMPCAJCOM, PECAJCOM
	WHERE CCO_COD = ECC_FPE_COD
	AND ECC_EMP_COD = '".$_SESSION["fun_cod"]."'
	and ecc_estado='A'";
?>