<?
// Mensajes de error.
$error_login_ms[0]="En este momento no es posible acceder al sistema.";
$error_login_ms[1]="No se pudo realizar consulta a la Base de datos.";
//$error_login_ms[2]="Clave de Usuario no existe.";
$error_login_ms[2]="<font color='#FF0000'>Imposible iniciar sesi&oacute;n! Verifique Usuario y/o clave.</font>";
//$error_login_ms[3]="Clave no v&aacute;lida.";
$error_login_ms[3]="<font color='#FF0000'>Imposible iniciar sesi&oacute;n! Verifique Usuario y/o clave.</font>";
//$error_login_ms[4]="Usuario no existe.";
$error_login_ms[4]="<font color='#FF0000'>Imposible iniciar sesi&oacute;n! Verifique Usuario y/o clave.</font>";
$error_login_ms[5]="No est&aacute; autorizado para entrar en esta p&aacute;gina.";
$error_login_ms[6]="Acceso no autorizado! Registrese.";
//$error_login_ms[7]="<b><font color='#FF0000'>Usuario Inactivo.</font></b>";
$error_login_ms[7]="<font color='#FF0000'>Imposible iniciar sesi&oacute;n! Verifique Usuario y/o clave.</font>";
$error_login_ms[8]="<font color='#FF0000'>No existe un registro de ese correo.</font>";
$error_login_ms[9]="<font color='#3366FF'>La clave ha sido enviada a su correo.</font>";
$error_login_ms[10]="<font color='#FF0000'>Digite su usuario.</font>";
$error_login_ms[11]="<font color='#FF0000'>Digite la carrera.</font>";
$error_login_ms[12]="<font color='#FF0000'>Las claves son diferentes.</font>";
$error_login_ms[13]="<font color='#3366FF'>La clave ha sido cambiada.</font>";
$error_login_ms[14]="<font color='#FF0000'>El tipo de usuario no corresponde.</font>";
$error_login_ms[15]="<font color='#FF0000'>Digite el e-mail.</font>";
$error_login_ms[16]="<font color='#FF0000'>El e-mail que escribio no es correcto.</font>";
$error_login_ms[17]="<font color='#FF0000'>Los campos con asterisco no pueden ser nulos.</font>";
$error_login_ms[18]="<font color='#3366FF'>..............: El E-mail ha sido enviado. :...............</font>";
$error_login_ms[19]="<font color='#FF0000'>..............: Digite el nombre. :...............</font>";
$error_login_ms[20]="<font color='#FF0000'>..............: Digite el asunto. :...............</font>";
$error_login_ms[21]="<font color='#3366FF'>..............: Registro insertado. :...............</font>";
$error_login_ms[22]="<font color='#3366FF'>..............: Registro borrado. :...............</font>";
$error_login_ms[23]="<font color='#FF0000'>..............: El registro ya existe. :...............</font>";
$error_login_ms[24]="<font color='#FF0000'>..............: Digite el dato a consultar. :...............</font>";
$error_login_ms[25]="<font color='#FF0000'><b>..............: No hay registros para esta consulta. :...............</b></font>";
$error_login_ms[26]="<font color='#FF0000'><b>..............: El grupo que seleccion, est&aacute; lleno. :...............</b></font>";
$error_login_ms[27]="<font color='#FF0000'><b>..............: Fin del proceso. :...............</b></font>";
$error_login_ms[28]="..............: No hay claves para encriptar. :...............";
$error_login_ms[29]="<font color='#FF0000'><b>...........: Complete el formulario. :............</b></font>";
$error_login_ms[30]="<font color='#FF0000'><b>...........: No hay registros para borrar. :............</b></font>";
$error_login_ms[31]="<font color='#3366FF'><b>...........: El documento ha sido actualizado. :............</b></font>";
$error_login_ms[32]="<font color='#FF0000'><b>...........: Por favor cambie la clave. :............</b></font>";
$error_login_ms[33]="<font color='#FF0000'><b>...........: No hay usuarios nuevos. :............</b></font>";
$error_login_ms[34]="<font color='#FF0000'><b>...........: El valor a ingresar debe ser numerico. :............</b></font>";
$error_login_ms[35]="<font color='#FF0000'><b>...........: Los valores  a ingresar no corresponde. :............</b></font>";
$error_login_ms[100]="<font color='#FF0000'><b>...........: Asignatura inscrita. :............</b></font>";
$error_login_ms[101]="<font color='#FF0000'><b>...........: Asignatura presenta cruce con otra ya inscrita. :............</b></font>";
$error_login_ms[102]="<font color='#FF0000'><b>...........: Inscriba s&oacute;lo el n&uacute;mero de asignaturas permitidas en su Proyecto Curricular. :............</b></font>";
$error_login_ms[103]="<font color='#FF0000'><b>...........: Usted tiene 3 &oacute; m&aacute;s asignaturas perdidas, solo se le permite inscribir las perdidas. :............</b></font>";
$error_login_ms[104]="<font color='#FF0000'><b>...........: Inscriba s&oacute;lo asignaturas del semestre que usted cursa &oacute; de semestres inferiores. :............</b></font>";
$error_login_ms[105]="<font color='#FF0000'><b>...........: Esta asignatura ya esta inscrita. Seleccione otra. :............</b></font>";
$error_login_ms[106]="<font color='#FF0000'><b>...........: Ya no hay cupo para esta asignatura y grupo. Seleccione otro grupo. :............</b></font>";
$error_login_ms[107]="<font color='#FF0000'><b>...........: No puede cancelar una asignatura que fue reprobada. :............</b></font>";
$error_login_ms[108]="<font color='#FF0000'><b>...........: Asignatura cancelada. :............</b></font>";
$error_login_ms[109]="Demasiadas Conexiones.";
//$error_login_ms[110]="Usuario inhabilitado para esta franja horaria.";
$error_login_ms[110]="Señor(a) Usuario(a), usted est&aacute; ingresando en una franja que no le corresponde!<br>Por favor, consulte el calendario de franjas.";
$error_login_ms[111]="La base de datos se encuentra ocupada. Por favor intente mas tarde.";
$error_login_ms[112]="Lo sentimos! El sistema esta atendiendo el n&uacute;mero m&aacute;ximo de usuarios permitidos..<br>Por favor, intente en algunos minutos";
$error_login_ms[113]="El tiempo de trabajo ha expirado..<br>La sesi&oacute;n ha sido cerrada!";
$error_login_ms[114]="Acceso Restrigido";
$error_login_ms[115]="<b>Acceso incorrecto!</b>";
$error_login_ms[116]="Franja exclusiva para acceso a Coordinadores";
$error_login_ms[117]="Debe Ingresar el C&oacute;digo de Validaci&oacute;n";
$error_login_ms[118]="C&oacute;digo de Validaci&oacute;n Incorrecto";

?>
