<?php
$docnroiden = $_SESSION['usuario_login'];
$cod_consul = "SELECT DISTINCT CUR_ASI_COD,
		ASI_NOMBRE,
		(lpad(cur_cra_cod::text,3,'0')||'-'||cur_grupo) CUR_NRO,
		CUR_CRA_COD,
		CRA_NOMBRE,
		CAR_DOC_NRO,
		DOC_NOMBRE ||' '||DOC_APELLIDO,
		APE_ANO,
		APE_PER,
		CASE WHEN INS_SEM=0 THEN 'Electiva'
		WHEN INS_SEM=98 THEN 'CP'
		ELSE TO_CHAR(INS_SEM,'999') END CUR_SEMESTRE,
		CUR_NRO_CUPO,
		CUR_NRO_INS,
		INS_EST_COD,
		EST_NOMBRE,
		INS_NOTA,
		INS_OBS,
		CUR_ID
		FROM ACCARGAS
		INNER JOIN ACHORARIOS ON CAR_HOR_ID=HOR_ID
		INNER JOIN ACCURSOS ON HOR_ID_CURSO=CUR_ID
		INNER JOIN ACASI ON ASI_COD=CUR_ASI_COD
		INNER JOIN ACCRA ON CUR_CRA_COD=CRA_COD
		INNER JOIN ACDOCENTE ON CAR_DOC_NRO=DOC_NRO_IDEN
		INNER JOIN ACASPERI ON APE_ANO=CUR_APE_ANO AND APE_PER=CUR_APE_PER
		INNER JOIN ACINS ON INS_ASI_COD=CUR_ASI_COD AND INS_ANO=CUR_APE_ANO AND INS_PER=CUR_APE_PER AND INS_GR=CUR_ID
		INNER JOIN ACEST ON EST_COD=INS_EST_COD
		WHERE CUR_ASI_COD =".$_SESSION["A"]."
		AND CUR_ID =".$_SESSION["cur"]."
		AND CUR_CRA_COD =".$_SESSION["C"]."
		AND CAR_DOC_NRO = $docnroiden
		AND APE_ESTADO = '$estado'
		ORDER BY INS_EST_COD";
?>
