<?PHP
//NOVEDADES
$sqlnoved = "SELECT NOV_CON_TIPO,
	NOV_CON_COD,
	CON_NOMBRE,
	NOV_NRO_SEC,
        CASE WHEN CON_UNIDADES='V' THEN 'VALOR' WHEN CON_UNIDADES='P' THEN 'PORCENTAJE' ELSE '' END UNIDADES,
	NOV_VALOR,
        CASE WHEN NOV_CUOTAS=999 THEN 0 ELSE NOV_CUOTAS END CUOTAS,
	TO_CHAR(NOV_FECHA,'YYYY-Mon-DD'),
        CASE WHEN NOV_ESTADO='A' THEN 'Activo' WHEN NOV_ESTADO='I' THEN 'Inactivo' ELSE '' END ESTADO,
	TO_CHAR(NOV_FECHA,'YYYYMMDD')
	FROM PRNOVEDHIS, PRCON
	WHERE CON_TIPO = NOV_CON_TIPO
	AND CON_COD = NOV_CON_COD
	AND NOV_EMP_COD = ".$_SESSION["fun_cod"]."
	AND NOV_CON_TIPO IN(".$_POST['NovConTipo'].")
	AND NOV_ESTADO = '$estado'
	ORDER BY 1,2,4,10";
?>