<?PHP
$hiscar = "SELECT CAR_NOMBRE Cargo,
	HCA_DEP_COD_PPTAL Adscrito, 
	DEP_NOMBRE Labora,
	DECODE(HCA_TIPO_VINCULACION, 'R','RESOLUCION','C','CONTRATO') TipVin,
	HCA_NRO_DOC_VINC DocVin,
	DECODE(HCA_TIPO_NOM, 1,'DEFINITIVA',2,'PROVISIONAL',3,'ENCARGO',4,'TEMPORAL',5,'PRUEBA',6,'COMISION',7,'PENSIONADO') TipNom, 
	TO_CHAR(HCA_DESDE, 'DD-Mon-YYYY') Desde,
	TO_CHAR(HCA_HASTA, 'DD-Mon-YYYY') Hasta,
	TO_CHAR(HCA_FECHA_DOCUMENTO, 'DD-Mon-YYYY') FecDoc,
	TO_CHAR(HCA_FECHA_ACTA_POS, 'DD-Mon-YYYY') FecActa,
	HCA_NRO_ACTA_POS NroActa,
	HCA_ESTADO Est
	FROM mntpe.PEHISCAR, mntpe.PECARGO, GEDEP
	WHERE HCA_EMP_COD = ".$_SESSION["fun_cod"]."
	AND CAR_COD = HCA_CAR_COD
	AND DEP_COD = HCA_DEP_COD_LAB";
?>