<?PHP
$datos = "SELECT EMP_COD,
	fua_invierte_nombre(EMP_NOMBRE),
	EMP_NRO_IDEN,
	DECODE(EMP_TIPO_IDEN, 1,'CEDULA DE CIUDADANIA', 2, 'TARJETA DE IDENTIDAD', 3, 'CEDULA DE EXTRANJERIA', 4, 'OTROS'), 
	FUA_NOMBRE_LUGAR(EMP_LUG_COD_IDEN),
	FUA_NOMBRE_LUGAR(EMP_LUG_COD_NAC),
	TO_CHAR(EMP_FECHA_NAC, 'DD-Mon-YYYY'),
	DECODE(EMP_SEXO,'M','MASCULINO', 'F', 'FEMENINO'),
	DECODE(EMP_ESTADO_CIVIL, 1,'SOLTERO', 2,'CASADO', 3,'UNION LIBRE', 4,'SEPARADO', 5,'VIUDO'),
	EMP_DIRECCION,
	FUA_NOMBRE_LUGAR(EMP_LUG_COD_DOM),
	EMP_TELEFONO,
	EMP_TELEFONO_ALT,
	TO_CHAR(EMP_DESDE, 'DD-Mon-YYYY'),
	DECODE(EMP_REGIMEN,'A','ANTIGUO', 'N', 'NUEVO'),
	CAR_NOMBRE,
	DEP_NOMBRE,
	TO_CHAR(CAR_SUELDO, '$999,999,999.99') BASICO,
	trunc(MONTHS_BETWEEN(fua_fecha_sys,EMP_FECHA_NAC)/12),
	trunc(MONTHS_BETWEEN(fua_fecha_sys,EMP_DESDE)/12),
	EMP_EMAIL
	FROM PEEMP, PECARGO, GEDEP
	WHERE EMP_NRO_IDEN = $funcod
	AND CAR_COD = EMP_CAR_COD
	AND DEP_COD = EMP_DEP_COD";
?>