<?PHP
$hiscar = "SELECT CAR_NOMBRE Cargo,
	HCA_DEP_COD_PPTAL Adscrito, 
	DEP_NOMBRE Labora,
	(CASE WHEN HCA_TIPO_VINCULACION =  'R' THEN 'RESOLUCION'WHEN HCA_TIPO_VINCULACION = 'C' THEN 'CONTRATO' END) TipVin,
	HCA_NRO_DOC_VINC DocVin,
	(CASE WHEN HCA_TIPO_NOM =  1 THEN 'DEFINITIVA' WHEN HCA_TIPO_NOM = 2 THEN 'PROVISIONAL' WHEN HCA_TIPO_NOM = 3 THEN 'ENCARGO' WHEN HCA_TIPO_NOM = 4 THEN 'TEMPORAL' WHEN HCA_TIPO_NOM = 5 THEN 'PRUEBA' WHEN HCA_TIPO_NOM = 6 THEN 'COMISION' WHEN HCA_TIPO_NOM = 7 THEN 'PENSIONADO' END) TipNom, 
	TO_CHAR(HCA_DESDE, 'DD-Mon-YYYY') Desde,
	TO_CHAR(HCA_HASTA, 'DD-Mon-YYYY') Hasta,
	TO_CHAR(HCA_FECHA_DOCUMENTO, 'DD-Mon-YYYY') FecDoc,
	TO_CHAR(HCA_FECHA_ACTA_POS, 'DD-Mon-YYYY') FecActa,
	HCA_NRO_ACTA_POS NroActa,
	HCA_ESTADO Est
	FROM mntpe.PEHISCAR, mntpe.PECARGO, GEDEP
	WHERE HCA_EMP_COD = ".$_SESSION["fun_cod"]."
	AND CAR_COD = HCA_CAR_COD
	AND DEP_COD = HCA_DEP_COD_LAB";
?>