<?PHP
$QryObs = "SELECT DPO_APE_ANO, 
	DPO_APE_PER, 
	DPO_DOC_NRO_IDEN, 
	DPO_OBS, 
	DPO_ESTADO
	FROM ACDOCPLANTRABAJOBS
	WHERE DPO_APE_ANO = $ano
	AND DPO_APE_PER = $per
	AND DPO_DOC_NRO_IDEN = ".$_SESSION['usuario_login']."
	AND DPO_ESTADO = 'A'";
?>