<?PHP
$confecnot = "SELECT NPF_CRA_COD,
	TO_NUMBER(TO_CHAR(NPF_IPAR1, 'YYYYMMDD')),
	TO_NUMBER(TO_CHAR(NPF_FPAR1, 'YYYYMMDD')),
	TO_NUMBER(TO_CHAR(NPF_IPAR2, 'YYYYMMDD')), 
	TO_NUMBER(TO_CHAR(NPF_FPAR2, 'YYYYMMDD')),
	TO_NUMBER(TO_CHAR(NPF_IPAR3, 'YYYYMMDD')), 
	TO_NUMBER(TO_CHAR(NPF_FPAR3, 'YYYYMMDD')),
	TO_NUMBER(TO_CHAR(NPF_IPAR4, 'YYYYMMDD')), 
	TO_NUMBER(TO_CHAR(NPF_FPAR4, 'YYYYMMDD')),
	TO_NUMBER(TO_CHAR(NPF_IPAR5, 'YYYYMMDD')), 
	TO_NUMBER(TO_CHAR(NPF_FPAR5, 'YYYYMMDD')),
	TO_NUMBER(TO_CHAR(NPF_ILAB, 'YYYYMMDD')), 
	TO_NUMBER(TO_CHAR(NPF_FLAB, 'YYYYMMDD')),
	TO_NUMBER(TO_CHAR(NPF_IEXA, 'YYYYMMDD')),  
	TO_NUMBER(TO_CHAR(NPF_FEXA, 'YYYYMMDD')),
	TO_NUMBER(TO_CHAR(NPF_IHAB, 'YYYYMMDD')),
	TO_NUMBER(TO_CHAR(NPF_FHAB, 'YYYYMMDD')),
	TO_NUMBER(TO_CHAR(ACE_FEC_FIN, 'YYYYMMDD'))
	FROM acnotparfec, accaleventos
	WHERE NPF_CRA_COD = ".$_SESSION["C"]."
	AND NPF_ESTADO = 'A'
	AND ace_anio = $ano
	AND ace_periodo = $per
	AND ace_cra_cod = npf_cra_cod
	AND ace_cod_evento = 7";
	
	echo "a&ntilde;o: ".$ano."periodo: ".$per."carrera: ".$_SESSION["C"];

?>
