<?PHP
$cursos = "SELECT EA_NOMBRE_CURSO, 
	EA_NOMBRE_INST, 
	EA_NRO_HORAS, 
	TO_CHAR(EA_DESDE, 'DD-MON-YYYY'), 
	TO_CHAR(EA_HASTA, 'DD-MON-YYYY'), 
	DECODE(EA_ESTADO, 'A','ACTIVO','I','INACTIVO')
	FROM mntpe.PEESTACT
	WHERE EA_EMP_COD = ".$_SESSION["fun_cod"]."
	ORDER BY 3";
?>