<?PHP
//NOVEDADES
$sqlnoved = "SELECT NOV_CON_TIPO,
		NOV_CON_COD,
		CON_NOMBRE,
		NOV_NRO_SEC,
		DECODE(CON_UNIDADES, 'V','VALOR','P','PORCENTAJE'),
		NOV_VALOR,
		DECODE(NOV_CUOTAS, 999,0, NOV_CUOTAS),
		TO_CHAR(NOV_FECHA,'DD-Mon-YYYY'),
		decode(NOV_ESTADO, 'A','Activo','I','Inactivo'),
		TO_CHAR(NOV_FECHA,'YYYYMMDD')
		FROM $prnovedades, PRCON
		WHERE CON_TIPO = NOV_CON_TIPO
		AND CON_COD = NOV_CON_COD
		AND NOV_EMP_COD = ".$_SESSION["fun_cod"]."
		AND NOV_ESTADO = '$estado'
		ORDER BY 1,2,10 ASC";
?>