<?PHP
//CARGO ACTUAL
$cargo = "SELECT CAR_COD,
	CAR_NIV,
	CAR_GRA,
	CAR_NOMBRE,
	ESA_SUELDO
	FROM mntpe.PECARGO, mntpe.PEEMP, mntpe.PREMPSAL
	WHERE CAR_COD = EMP_CAR_COD
	AND EMP_COD = ".$_SESSION["fun_cod"]."
	AND ESA_COD = EMP_COD
	AND CAR_ESTADO = 'A'";
?>